### ISSUE TITLE
Uso de URL Path através do NGINX

### ISSUE THREAD

**Issue by lc-rezende** [EvolutionAPI/evolution-api#1010]
Boa tarde. 

Estou tentando instalar a Evolution API 2.0 em um servidor que está rodando o NGINX e configurei a seguinte location:

```
        location /evolution/ {
		proxy_pass http://localhost:8090/;
		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection 'upgrade';
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-Proto $scheme;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_cache_bypass $http_upgrade;
	}


  	location /manager/ {
		proxy_pass http://localhost:8090/manager/;
		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection 'upgrade';
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-Proto $scheme;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_cache_bypass $http_upgrade;
	}
```

No meu docker-compose.yml e configurei os seguintes parâmetros:

```
evolution-api:
    container_name: evolution_api
    image: atendai/evolution-api:v2.1.1
    restart: always
    networks:
      - evolution-net
    environment:
      ...
      - SERVER_PORT=8090
      - SERVER_URL=https://sub.meudominio.com.br/
      - ...
```

Quando eu acesso `https://sub.meudominio.com.br/evolution/` eu vejo a mensagem de sucesso:

```
{
  "status": 200,
  "message": "Welcome to the Evolution API, it is working!",
  "version": "2.1.1",
  "clientName": "evolution_exchange",
  "manager": "https://sub.meudominio.com.br/manager",
  "documentation": "https://doc.evolution-api.com"
}
```

Porém, quando acesso `https://sub.meudominio.com.br/manager/` a página fica em branco. Imagino que porque recursos internos não reconhecem esse path. 

- https://sub.meudominio.com.br/assets/index-Do1bGWiz.js
- https://sub.meudominio.com.br/assets/index-DNOCacL_.css

Desculpa se é algo bobo, mas realmente já procurei nos issues e em outros fóruns mas não consigo resolver.

Por acaso isso seria alguma configuração de ambiente da Evo que estou deixando de declarar, ou estou declarando errado?
