### ISSUE TITLE
Falha nas migrations

### ISSUE THREAD

**Issue by lusabo** [EvolutionAPI/evolution-api#1115]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

Estou tentando rodar o EvolutionAPI localmente usando docker e estou obtendo o seguinte erro nos logs:

```
Deploying migrations for postgresql
Database URL: 
> evolution-api@2.2.0 db:deploy
> node runWithProvider.js "rm -rf ./prisma/migrations && cp -r ./prisma/DATABASE_PROVIDER-migrations ./prisma/migrations && npx prisma migrate deploy --schema ./prisma/DATABASE_PROVIDER-schema.prisma"
Environment variables loaded from .env
Prisma schema loaded from prisma/postgresql-schema.prisma
Datasource "db": PostgreSQL database "evolution", schema "public" at "postgres:5432"
Migration failed
...
```

Aqui está o **docker-compose.yml**:

```
services:
  evolution-api:
    container_name: evolution
    image: atendai/evolution-api:latest
    restart: always
    depends_on:
      - redis
      - postgres
    ports:
      - 8080:8080
    env_file:
      - .env
    volumes:
      - evolution_instances:/evolution/instances
    
  redis:
    image: redis:latest
    networks:
      - evolution-net
    container_name: redis
    command: >
      redis-server --port 6379 --appendonly yes
    volumes:
      - evolution_redis:/data
    ports:
      - 6379:6379

  postgres:
    container_name: postgres
    image: postgres:15
    networks:
      - evolution-net
    command: ["postgres", "-c", "max_connections=1000"]
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    networks:
      - evolution-net
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - 4000:80
    env_file:
      - .env

volumes:
  evolution_instances:
  evolution_redis:
  postgres_data:
  pgadmin_data:

networks:
  evolution-net:
    name: evolution-net
    driver: bridge
```

E o arquivo .env:

```
##### EVOLUTION
AUTHENTICATION_API_KEY=my-key

##### PGADMIN
PGADMIN_DEFAULT_EMAIL=my-email@gmail.com
PGADMIN_DEFAULT_PASSWORD=postgres

##### POSTGRESQL
DATABASE_ENABLED=true
DATABASE_PROVIDER=postgresql
DATABASE_CONNECTION_URI='postgresql://postgres:postgres@postgres:5432/evolution?schema=public'
DATABASE_CONNECTION_CLIENT_NAME=evolution
DATABASE_SAVE_DATA_INSTANCE=true
DATABASE_SAVE_DATA_NEW_MESSAGE=true
DATABASE_SAVE_MESSAGE_UPDATE=true
DATABASE_SAVE_DATA_CONTACTS=true
DATABASE_SAVE_DATA_CHATS=true
DATABASE_SAVE_DATA_LABELS=true
DATABASE_SAVE_DATA_HISTORIC=true

##### REDIS
CACHE_REDIS_ENABLED=true
CACHE_REDIS_URI=redis://localhost:6379/6
CACHE_REDIS_PREFIX_KEY=evolution
CACHE_REDIS_SAVE_INSTANCES=false
CACHE_LOCAL_ENABLED=false
```

Como resolver esse problema?

### What did you expect?

Que o Evolution rode localmente.

### What did you observe instead of what you expected?

As migrations falham.

### Which version of the API are you using?

latest

### What is your environment?

Mac
