### ISSUE TITLE
Webhook MESSAGES_UPSERT não dispara ao enviar mensagem via WhatsApp

### ISSUE THREAD

**Issue by lusabo** [EvolutionAPI/evolution-api#1120]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

Eu estou rodando o EvolutionAPI localmente no Docker e habilitei os webhooks SEND_MESSAGE e MESSAGES_UPSERT pelo manager. 

Criei uma aplicação Flask para testar esses webhooks com os seguintes endpoints:
@app.route('/evolutionapi-client/webhook/send-message', methods=['POST'])
@app.route('/evolutionapi-client/webhook/messages-upsert', methods=['POST'])

Ao mandar uma mensagem usando a API do Evolution (ex: http://localhost:8080/message/sendText/evolution-teste) o endpoint da aplicação associada ao webhook SEND_MESSAGE é executado.

Mas, ao enviar uma mensagem pelo meu Whatsapp ao número associado ao EvolutionAPI o webhook MESSAGES_UPSERT não é disparado e o endpoint associado a ele não é executado.

Nos logs não aparece nada.

### What did you expect?

O webhook MESSAGES_UPSERT seja disparado.

### What did you observe instead of what you expected?

Nada acontece. Inclusive já fiz o teste expondo na internet via ngrok tanto o Evolution quanto à minha aplicação Flask e o cenário foi o mesmo.

### Which version of the API are you using?

2.2.0

### What is your environment?

Docker rodando localmente.

```
services:
  evolution-api:
    container_name: evolution
    image: atendai/evolution-api:latest
    networks:
      - evolution-net
    restart: always
    depends_on:
      - redis
      - postgres
    ports:
      - 8080:8080
    env_file:
      - .env
    volumes:
      - evolution_instances:/evolution/instances
    
  redis:
    image: redis:latest
    networks:
      - evolution-net
    container_name: redis
    command: >
      redis-server --port 6379 --appendonly yes
    volumes:
      - evolution_redis:/data
    ports:
      - 6379:6379

  postgres:
    container_name: postgres
    image: postgres:15
    networks:
      - evolution-net
    command: ["postgres", "-c", "max_connections=1000"]
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    networks:
      - evolution-net
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - 4000:80
    env_file:
      - .env
  
  web:
    container_name: evolutionapi-client
    image: evolutionapi-client:latest
    networks:
      - evolution-net
    ports:
      - 3000:3000
    command: flask run --host=0.0.0.0 --port=3000
    environment:
    - FLASK_APP=app.py
    - FLASK_ENV=development

volumes:
  evolution_instances:
  evolution_redis:
  postgres_data:
  pgadmin_data:

networks:
  evolution-net:
    name: evolution-net
    driver: bridge
```

### Additional Notes

O aplicativo Flask criado com os endpoints pode ser visto aqui: https://github.com/lusabo/evolutionapi-client
