### ISSUE TITLE
[EN] unable to reply in WhatsApp group chats

### ISSUE THREAD

**Issue by patrickmau** [EvolutionAPI/evolution-api#1497]
### Bem-vido!

- [x] Sim, pesquisei problemas semelhantes no [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) e não encontrei nenhum.

### O que você fez?

I am using Chatwoot + Evolution API to send and receive message on my dedicated WhatsApp number.

As of yesterday, I am unable to post any chat replies into WhatsApp group chats, regardless if they have been created recently or a long time ago. Previously I was able to send messages into group chats if they were created recently, but not existing groups that were more than one month old.

### O que você esperava?

For chat messages to be posted as usual.

### O que vc observou ao invés do que esperava?

All messages to group chats fail with the above "The message could not be sent. Please check your connection. [object Object]" error.

Sending messages to contacts directly works fine, only group chats are affected by this.

### Capturas de Tela/Vídeos

<img width="542" alt="Image" src="https://github.com/user-attachments/assets/0d8266b4-ea05-4b06-952c-5db9bc12cc4b" />

![Image](https://github.com/user-attachments/assets/cf465624-5ef0-4e58-b4aa-a730c6c6082c)

<img width="1319" alt="Image" src="https://github.com/user-attachments/assets/5cad5e2a-a819-4c70-a1e1-2e9dd703ec9f" />

### Qual versão da API você está usando?

Server: Ubuntu 24.04 LTS
Chatwoot: v4.1.0
Evolution Api: 2.2.3

**docker-compose.yaml**
                                                                                     
```
services:
  api:
    container_name: evolution_api
    image: atendai/evolution-api:latest
    restart: always
    depends_on:
      - redis
      - postgres
    ports:
      - 8080:8080
    volumes:
      - evolution_instances:/evolution/instances
    networks:
      - evolution-net
    env_file:
      - .env
    expose:
      - 8080
    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis:
    image: redis:latest
    networks:
      - evolution-net
    container_name: redis
    command: >
      redis-server --port 6379 --appendonly yes
    volumes:
      - evolution_redis:/data
    ports:
      - 6379
    extra_hosts:
      - "host.docker.internal:host-gateway"
  postgres:
    container_name: postgres
    image: postgres:15
    networks:
      - evolution-net
    command: ["postgres", "-c", "max_connections=1000", "-c", "listen_addresses=*"]
    restart: always
    ports:
      - 5468:5432
    environment:
      - POSTGRES_USER=userid
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=evolution
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  evolution_instances:
  evolution_redis:
  postgres_data:


networks:
  evolution-net:
    name: evolution-net
    driver: bridge
```

### Qual é o seu ambiente?

LAMP setup running Ubuntu 24.04 LTS

### Outras expecificações do ambiente

PHP 8.2.28

### Se aplicável, cole a saída do log

```
[Evolution API]    v2.2.3  170   -  Sat May 24 2025 04:10:18     VERBOSE   [CacheEngine]  [string]  RedisCache initialized for Re 
[Evolution API]    v2.2.3  170   -  Sat May 24 2025 04:10:18     VERBOSE   [CacheService]  [string]  cacheservice created using cache engine: Gt 
[Evolution API]  [Chatwoot]  v2.2.3  170   -  Sat May 24 2025 04:10:19     VERBOSE   [ChannelStartupService]  [string]  Sending message to 120363403043191785@g.us 
[Evolution API]  [Chatwoot]  v2.2.3  170   -  Sat May 24 2025 04:10:19     VERBOSE   [ChannelStartupService]  [string]  Typing for 1200ms to 120363403043191785@g.us 
Cache request for group: 120363403043191785@g.us
[Evolution API]  [Chatwoot]  v2.2.3  170   -  Sat May 24 2025 04:10:21     VERBOSE   [ChannelStartupService]  [string]  Updating cache for group: 120363403043191785@g.us 
Cache request for group: 120363403043191785@g.us
[Evolution API]    v2.2.3  170   -  Sat May 24 2025 04:10:23     VERBOSE   [CacheEngine]  [string]  RedisCache initialized for Re 
[Evolution API]    v2.2.3  170   -  Sat May 24 2025 04:10:23     VERBOSE   [CacheService]  [string]  cacheservice created using cache engine: Gt 
[Evolution API]  [Chatwoot]  v2.2.3  170   -  Sat May 24 2025 04:10:24     ERROR   [ChannelStartupService]  [object]   
SessionError: No sessions
    at 260601586708638.1 [as awaitable] (/evolution/node_modules/libsignal/src/session_cipher.js:71:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async _asyncQueueExecutor (/evolution/node_modules/libsignal/src/queue_job.js:20:29) 

[Evolution API]    v2.2.3  170   -  Sat May 24 2025 04:10:24     VERBOSE   [ChatwootService]  [string]  onSendMessageError {"status":400,"error":"Bad Request","message":["SessionError: No sessions"]} 
[Evolution API]    v2.2.3  170   -  Sat May 24 2025 04:10:24     ERROR   [ChatwootService]  [object]   
{
  status: 400,
  error: 'Bad Request',
  message: [ 'SessionError: No sessions' ]
} 
```

### Notas Adicionais

**Evolution API .env file:**

```
# Whatsapp Web version for baileys channel
# https://web.whatsapp.com/check-update?version=0&platform=web

# WORKING
CONFIG_SESSION_PHONE_VERSION=2.3000.1023123818
# CONFIG_SESSION_PHONE_VERSION=2.3000.1022331021

# NOT WORKING
# CONFIG_SESSION_PHONE_VERSION=2.3000.1019707846
# CONFIG_SESSION_PHONE_VERSION=2.2413.51
```
