### ISSUE TITLE
webhook not working

### ISSUE THREAD

**Issue by suissa** [EvolutionAPI/evolution-api#203]
Eu tentei receber os eventos em http://localhost:6000/webhook mas não chega nada
Minha api está bem simples só para receber o webhook

```js
const express = require('express');
const cors = require('cors');
const bodyParser = require('body-parser');
const app = express();

// Ativando o CORS para todas as rotas
const corsOptions = {
  origin: '*', 
  optionsSuccessStatus: 200
};

app.use(bodyParser.json({ limit: '20mb' }));
app.use(bodyParser.urlencoded({ limit: '20mb', extended: true }));
app.use(cors(corsOptions));

app.post('/webhook', async (req, res) => {
  console.log('Requisição POST /webhook recebida');
  console.log('Requisição POST /webhook recebida req.body', req.body);
  res.send('Hello World webhook!');
});
// Inicia o servidor na porta 6000
app.listen(6000, () => {
  console.log('Servidor rodando na porta 6000');
});
```

Estou fazendo algo errado?

```
WEBHOOK:
  # Define a global webhook that will listen for enabled events from all instances
  GLOBAL:
    URL: http://localhost:6000/webhook
    ENABLED: true
    # With this option activated, you work with a url per webhook event, respecting the global url and the name of each event
    WEBHOOK_BY_EVENTS: false
  # Automatically maps webhook paths
  # Set the events you want to hear
  EVENTS:
    APPLICATION_STARTUP: false
    QRCODE_UPDATED: true
    MESSAGES_SET: true
    MESSAGES_UPSERT: true
    MESSAGES_UPDATE: true
    MESSAGES_DELETE: true
    SEND_MESSAGE: true
    CONTACTS_SET: false
    CONTACTS_UPSERT: false
    CONTACTS_UPDATE: false
    PRESENCE_UPDATE: false
    CHATS_SET: true
    CHATS_UPSERT: true
    CHATS_UPDATE: true
    CHATS_DELETE: true
    GROUPS_UPSERT: true
    GROUP_UPDATE: true
    GROUP_PARTICIPANTS_UPDATE: true
    CONNECTION_UPDATE: true
    CALL: true
    # This event fires every time a new token is requested via the refresh route
    NEW_JWT_TOKEN: false
    # This events is used with Typebot
    TYPEBOT_START: false
    TYPEBOT_CHANGE_STATUS: false
    # This event is used with Chama AI
    CHAMA_AI_ACTION: false
    # This event is used to send errors to the webhook
    ERRORS: false
    ERRORS_WEBHOOK: <url>
```
