### ISSUE TITLE
[Manager] Ao reiniciar a máquina as configurações de chatwoot e typebot somem

### ISSUE THREAD

**Issue by filiperochalopes** [EvolutionAPI/evolution-api#669]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

Ao reiniciar os containers as instâncias estão lá, também estão configurados os volumes corretamente, mas as configurações do chatwoot e do typebot somem, tendo que configurar novamente. Já entrei no container para verificar onde estariam essas configurações, para assim poder criar  um volume para eles, mas não encontrei. Estou falando dessas configurações:

![github_bug_evo](https://github.com/EvolutionAPI/evolution-api/assets/34348097/8c44e4b7-0f7f-4b23-93ec-ac48e2481752)

O comando que executo é `docker-compose down --remove-orphans --volumes`

Segue uma cópia de meu docker-compose.yml

```yml
services:
  evolution-api:
    container_name: adri_evolution_api
    image: atendai/evolution-api
    restart: always
    ports:
      - "8888:8080"
    env_file: .env
    volumes:
      - ./data/evolution-api/store:/evolution/store
      - ./data/evolution-api/instances:/evolution/instances
    depends_on:
      - mongo
      - evolution-redis

  evolution-redis:
    container_name: adri_evolution_redis
    image: redis
    restart: unless-stopped
    volumes:
      - ./data/redis:/data

  mongo:
    container_name: adri_evolution_db
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASS}
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo-db:/data

  typebot-db:
    image: postgres:14-alpine
    restart: always
    volumes:
      - ./data/psql-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB_NAME}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASS}

  typebot-builder:
    image: baptistearno/typebot-builder:latest
    restart: always
    depends_on:
      - typebot-db
    ports:
      - '3057:3000'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file: .env

  typebot-viewer:
    image: baptistearno/typebot-viewer:latest
    restart: always
    ports:
      - '3056:3000'
    env_file: .env

  chatwoot-base: &chatwoot-base
    image: chatwoot/chatwoot:latest
    env_file: .env.chatwoot
    volumes:
      - ./data/chatwoot/storage:/app/storage

  chatwoot-rails:
    <<: *chatwoot-base
    depends_on:
      - chatwoot-db
      - chatwoot-redis
    ports:
      - '${CHATWOOT_PORT}:3000'
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    entrypoint: docker/entrypoints/rails.sh
    command: ['bundle', 'exec', 'rails', 's', '-p', '3000', '-b', '0.0.0.0']

  sidekiq:
    <<: *chatwoot-base
    depends_on:
      - chatwoot-db
      - chatwoot-redis
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    command: ['bundle', 'exec', 'sidekiq', '-C', 'config/sidekiq.yml']

  chatwoot-db:
    image: postgres:12
    restart: always
    env_file: .env.chatwoot
    volumes:
      - ./data/chatwoot/postgres:/var/lib/postgresql/data


  chatwoot-redis:
    image: redis:alpine
    restart: always
    command: ["sh", "-c", "redis-server --requirepass \"$REDIS_PASSWORD\""]
    env_file: .env
    volumes:
      - ./data/chatwoot/redis:/data
```

### What did you expect?

Esperava que esses dados estivessem armazenados nos volumes `/instance` ou `/store` e assim fossem recuperados no restart.

### What did you observe instead of what you expected?

Que todas as configurações são excluídas.

### Which version of the API are you using?

1.8.1

### What is your environment?

Docker
