### ISSUE TITLE
Ao reiniciar o servidor no azure, todas as instâncias somem 

### ISSUE THREAD

**Issue by brunofalcao** [EvolutionAPI/evolution-api#850]
### Welcome!

- [X] Yes, I have searched for similar issues on [GitHub](https://github.com/EvolutionAPI/evolution-api/issues) and found none.

### What did you do?

Quando preciso realizar algum ajuste ou manutenção no meu servidor da Azure e reinicio ele, a evolution funciona normal mas volta totalmente zerada.
Hoje utilizo no easypanel com docker
Alguém sabe como salvar as instâncias e restaurar depois?

### What did you expect?

Espero que quando precisar parar ou reiniciar meu servidor, volte com as instâncias

### What did you observe instead of what you expected?

.

### Which version of the API are you using?

2.0.10

### What is your environment?

Linux

### Other environment specifications

.

**Comment by vagkaefer** [comment]
@brunofalcao Como você está usando o docker? Iniciando com docker run ou usando docker compose?

Se for docker run, pode nos mostrar o comando completo? 

Se for docker-compose, pode nos mostrar ele?

**Comment by brunofalcao** [comment]
Olá @vagkaefer! 
Hoje uso o docker run, no easypanel
eu crio através de template, 
a forma como eu instalo é essa: https://github.com/comunidadehubconnect/easypanelevolution
Eu acredito que seja algo do Redis, que as instâncias fiquem gravadas no Redis e não no postgres, faz sentido?

**Comment by vagkaefer** [comment]
Então @brunofalcao, docker por padrão é volátil, então você tem que verificar os volumes e também precisa ver o arquivo de configuração, nele tem opção de usar postgres para persistir dados, provavelmente está faltando isso.

Tua reclamação de dados sumindo é um dos itens acima ou ambos,  não é diretamente relacionado ao Evolution e também não parece ser um bug. 

Eu crio, recrio, excluo, crio o ambiente de volta aqui usando docker e não perco nada, mas tenho volumes configurados nos containers e também configurei o postgres no arquivo de configuração, da uma revisada nesses pontos que teu problema será resolvido.

Se te ajudar, segue exemplo de volumes do evolution:

```
services:

  evolution:
    image: atendai/evolution-api:v2.1.2
    restart: unless-stopped
    ports:
      - 4000:8080
    volumes:
      - evolution_instances:/evolution/instances
      - evolution_store:/evolution/store
    env_file:
      - .env-evolution
    command: ["node", "./dist/src/main.js"]

  evolution-redis:
    image: redis:alpine
    restart: unless-stopped
    command: redis-server
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      
volumes:
  evolution_instances:
  evolution_store:

```
PS: Redis não precisa volume, é só cache

A parte do postgres no .env

```
# Provider: postgresql | mysql
DATABASE_PROVIDER=postgresql
DATABASE_CONNECTION_URI='postgresql://usernameHere:passwordHere@192.168.124.36:5432/evolution?schema=public'
```
